project: 
  type: website

title: "R User Meet Amsterdam UMC" # change me
theme: code-cafe.scss

website: 
  navbar: 
    logo: assets/img/aumc.png #logo.png
    right: 
      - href: about.qmd
      - href: meetups/index.qmd
      - icon: github
        aria-label: Link to Code Cafe NL GitHub organisation
        href: https://github.com/AmsterdamUMC/rum-umc